CREATE ROLE IF NOT EXISTS {{ BENCHMARK_ROLE }};

CREATE DATABASE IF NOT EXISTS {{ BENCHMARK_DATABASE }};
CREATE SCHEMA IF NOT EXISTS {{ BENCHMARK_DATABASE }}.TPCH_SF1;
CREATE SCHEMA IF NOT EXISTS {{ BENCHMARK_DATABASE }}.TPCH_SF10;
CREATE SCHEMA IF NOT EXISTS {{ BENCHMARK_DATABASE }}.TPCH_SF100;
CREATE SCHEMA IF NOT EXISTS {{ BENCHMARK_DATABASE }}.TPCH_SF1000;

CREATE USER IF NOT EXISTS {{ BENCHMARK_USER }}
  TYPE = SERVICE
  DEFAULT_ROLE = {{ BENCHMARK_ROLE }}
  DEFAULT_WAREHOUSE = {{ BENCHMARK_WAREHOUSE }}
  DEFAULT_NAMESPACE = '{{ BENCHMARK_DATABASE }}.TPCH_SF1'
  COMMENT = 'Service user for dlthubarrow benchmark container app';

GRANT ROLE {{ BENCHMARK_ROLE }} TO USER {{ BENCHMARK_USER }};
GRANT USAGE ON WAREHOUSE {{ BENCHMARK_WAREHOUSE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT OPERATE ON WAREHOUSE {{ BENCHMARK_WAREHOUSE }} TO ROLE {{ BENCHMARK_ROLE }};

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE {{ BENCHMARK_ROLE }};

GRANT USAGE ON DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
GRANT MODIFY ON ALL SCHEMAS IN DATABASE {{ BENCHMARK_DATABASE }} TO ROLE {{ BENCHMARK_ROLE }};
