ALTER USER IF EXISTS {{ BENCHMARK_USER }} ADD PROGRAMMATIC ACCESS TOKEN {{ PAT_NAME }}
  ROLE_RESTRICTION = '{{ BENCHMARK_ROLE }}'
  DAYS_TO_EXPIRY = {{ DAYS_TO_EXPIRY }}
  COMMENT = 'PAT for dlthubarrow benchmark container app';
